services:
  app:
    build: . # Ceci utilise le Dockerfile local au lieu de pull depuis GHCR
    container_name: prisonerDilemma-app-local
    ports:
      - "8080:8080"
    networks:
      - shared-network
    restart: unless-stopped
networks:
  shared-network:
    external: true